#!/bin/bash

TOPIC=${1:-test-kafka}
docker exec -it sp-kafka \
    /usr/bin/kafka-topics \
    --bootstrap-server sp-kafka:19092 \
    --create --topic $TOPIC \
    --replication-factor 1 --partitions 10
echo "> list topics"
docker exec -it sp-kafka \
    /usr/bin/kafka-topics \
    --bootstrap-server sp-kafka:19092 --list