version: "3"

networks:
  sptest:
    driver: bridge

services:
  sp-kdc:
    image: sequenceiq/kerberos:latest
    container_name: sp-kdc
    hostname: sp-kdc
    networks:
      - sptest
    environment:
      TZ: Asia/Shanghai
      REALM: SPTEST.COM
      DOMAIN_REALM: sptest.com
      KERB_MASTER_KEY: masterkey
      KERB_ADMIN_USER: admin
      KERB_ADMIN_PASS: admin
    volumes:
      - ${SP_CONF_DIR:-./conf}/kerberos/config.sh:/config.sh
      - ${SP_CONF_DIR:-./conf}/keytabs:/etc/kerberos
      - ${SP_LOG_DIR:-./log}/kerberos:/var/log/kerberos
      - /dev/urandom:/dev/random

  sp-zk:
    image: confluentinc/cp-zookeeper:5.2.0
    container_name: sp-zk
    hostname: sp-zk
    restart: always
    networks:
      - sptest
    depends_on:
      - sp-kdc
    environment:
      TZ: Asia/Shanghai
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: "sp-zk:2888:3888"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/security/keytabs/zookeeper_jaas.conf -Djava.security.krb5.conf=/etc/security/keytabs/krb5.conf -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider -Dsun.security.krb5.debug=true"
    volumes:
      - ${SP_CONF_DIR:-./conf}/keytabs:/etc/security/keytabs
      - /dev/urandom:/dev/random
    security_opt:
      - label:disable

  sp-kafka:
    image: confluentinc/cp-kafka:5.2.0
    container_name: sp-kafka
    restart: always
    hostname: sp-kafka
    networks:
      - sptest
    depends_on:
      - sp-zk
      - sp-kdc
    ports:
      - ${SP_KAFKA_PORT}:${SP_KAFKA_PORT}
    environment:
      TZ: Asia/Shanghai
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://${SP_KAFKA_HOST}:${SP_KAFKA_PORT},INSIDE://sp-kafka:19092,SECURT://sp-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT,SECURT:SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: GSSAPI
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: sp-zk:2181
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/security/keytabs/broker_jaas.conf -Djava.security.krb5.conf=/etc/security/keytabs/krb5.conf -Dsun.security.krb5.debug=true"
    volumes:
      - ${SP_CONF_DIR:-./conf}/keytabs:/etc/security/keytabs
      - /dev/urandom:/dev/random
    security_opt:
      - label:disable
