version: "2.3"

services:
  sp-clickhouse:
    image: clickhouse/integration-test:latest
    container_name: sp-clickhouse
    hostname: clickhouse
    ports:
      - 9000:9000
    environment:
      TZ: Asia/Shanghai
      CLICKHOUSE_WATCHDOG_ENABLE: 0
      CLICKHOUSE_NATS_TLS_SECURE: 0
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ${SP_BIN_DIR}/clickhouse:/usr/bin/clickhouse
      - ${SP_WORKDIR}/docker/conf:/etc/clickhouse-server/
      - ${SP_WORKDIR}/docker/data:/var/lib/clickhouse/
      - ${SP_WORKDIR}/docker/log:/var/log/clickhouse-server/
    entrypoint: bash -c "trap 'pkill tail' INT TERM; clickhouse server --config-file=/etc/clickhouse-server/config.xml --log-file=/var/log/clickhouse-server/clickhouse-server.log --errorlog-file=/var/log/clickhouse-server/clickhouse-server.err.log --daemon; coproc tail -f /dev/null; wait $$!"
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_NICE
      # for umount/mount on fly
      - SYS_ADMIN
