#!/usr/bin/env python

from confluent_kafka import Producer
import socket
from multiprocessing import Pool

TOPIC="test"
conf = {
    'bootstrap.servers': 'localhost:29092',
    'client.id': socket.gethostname()
}

producer = Producer(conf)
print(producer.list_topics(TOPIC).topics)
try:
    producer.produce(TOPIC, key="key", value="value")
    producer.flush()
except Exception as e:
    print("error")
    
    
    2020-12-23 14:45:31|100|Test